// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeMjIB8g9tb-thsHIFED4i-Z8YLhQ2cFE',
    appId: '1:1017548709119:web:f3e1f0ecfb116393afc0ca',
    messagingSenderId: '1017548709119',
    projectId: 'bashair-17414',
    authDomain: 'bashair-17414.firebaseapp.com',
    storageBucket: 'bashair-17414.appspot.com',
    measurementId: 'G-V253PY237V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD00P6H-jvApkG8EjGaBSYY3WCHd_i0p84',
    appId: '1:1017548709119:android:6e71d15f623f096bafc0ca',
    messagingSenderId: '1017548709119',
    projectId: 'bashair-17414',
    storageBucket: 'bashair-17414.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDguS1H4bP2-eQxnkG26tEV5Ns7hADgCLk',
    appId: '1:1017548709119:ios:5b6e9c73dde45e79afc0ca',
    messagingSenderId: '1017548709119',
    projectId: 'bashair-17414',
    storageBucket: 'bashair-17414.appspot.com',
    iosBundleId: 'com.example.bashairProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDguS1H4bP2-eQxnkG26tEV5Ns7hADgCLk',
    appId: '1:1017548709119:ios:41c890af519de2c2afc0ca',
    messagingSenderId: '1017548709119',
    projectId: 'bashair-17414',
    storageBucket: 'bashair-17414.appspot.com',
    iosBundleId: 'com.example.bashairProject.RunnerTests',
  );
}
